# Netlify Deploy Contexts

[build]
  command = "mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = 3.8

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options         = "DENY"
    X-Content-Type-Options  = "nosniff"
    X-XSS-Protection        = "1; mode=block"

[[redirects]]
  from    = "https://hue-api.netlify.app/*"
  to      = "https://hue-api.nirantak.com/:splat"
  status  = 301
  force   = true
